### ISSUE TITLE
Failed playFromId

### ISSUE THREAD

**Issue by albertloubet** [gafsel/flutter_plugin_playlist#2]
When I try use play() with PlaylistItemOptions but I have this problem:

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String at org.gafs.flutter_plugin_playlist.PlaylistItemOptions.<init>(PlaylistItemOptions.java:22) at org.gafs.flutter_plugin_playlist.FlutterPluginPlaylistPlugin.onMethodCall(FlutterPluginPlaylistPlugin.java:93) at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222) at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:326)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
execute: play: ===> null

`await instance.player.setPlaylistItems(audios,
      options: PlaylistItemOptions(
        startPaused: false,
        playFromId: id,
      ),
    );`

playFromId: id is a num.

**Comment by gafsel** [comment]
Hey there @albertloubet 

Thanks for the heads up. Working on it and hoping to release the new version in a couple of days.

**Comment by gafsel** [comment]
@albertloubet fixed on release v0.1.1!

**Comment by albertloubet** [comment]
Thanks @gafsel :)
