### ISSUE TITLE
 Error conflicts with video_player and cash app

### ISSUE THREAD

**Issue by finn9617** [gafsel/flutter_plugin_playlist#29]
![image](https://user-images.githubusercontent.com/24228885/78377819-52399280-75fa-11ea-8387-5c333bc5333b.png)
![image](https://user-images.githubusercontent.com/24228885/78377870-654c6280-75fa-11ea-8dd4-68bc4b7876c6.png)

**Comment by gafsel** [comment]
Hi there @nguyenlaai9 ,

It looks like a dependency conflict as the flutter_plugin_playlist uses the exoplayer 2.6.1 and the video_player uses the exoplayer 2.6.9. But I'll have to take a better look to be certain and fix the problem.

**Comment by gafsel** [comment]
If you have the time, add these dependencies to you build.gradle in the app folder:

```
        implementation "com.google.android.exoplayer:exoplayer-core:2.6.1"
        implementation "com.google.android.exoplayer:exoplayer-dash:2.6.1"
        implementation "com.google.android.exoplayer:exoplayer-hls:2.6.1"
        implementation "com.google.android.exoplayer:exoplayer-smoothstreaming:2.6.1"
        implementation "com.google.android.exoplayer:extension-okhttp:2.6.1"
```

If anything changes let me know.

**Comment by kebsont** [comment]
Hello @gafsel , I tried to add these dependencies but still got the same error.
```logs
W/Glide   ( 8528): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
D/NetworkSecurityConfig( 8528): Using Network Security Config from resource network_security_config debugBuild: true
W/daarayislam.ap( 8528): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/daarayislam.ap( 8528): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/daarayislam.ap( 8528): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
D/AndroidRuntime( 8528): Shutting down VM
E/AndroidRuntime( 8528): FATAL EXCEPTION: main
E/AndroidRuntime( 8528): Process: com.daarayislam.app, PID: 8528
E/AndroidRuntime( 8528): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/drm/DefaultDrmSessionManager$EventListener;
E/AndroidRuntime( 8528): 	at com.devbrackets.android.exomedia.core.audio.ExoAudioPlayer.<init>(ExoAudioPlayer.java:62)
E/AndroidRuntime( 8528): 	at com.devbrackets.android.exomedia.AudioPlayer.<init>(AudioPlayer.java:64)
E/AndroidRuntime( 8528): 	at com.devbrackets.android.exomedia.AudioPlayer.<init>(AudioPlayer.java:60)
E/AndroidRuntime( 8528): 	at org.gafs.flutter_plugin_playlist.playlist.AudioApi.<init>(AudioApi.java:25)
E/AndroidRuntime( 8528): 	at org.gafs.flutter_plugin_playlist.service.MediaService.onCreate(MediaService.java:23)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime( 8528): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 8528): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8528): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8528): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 8528): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.drm.DefaultDrmSessionManager$EventListener" on path: DexPathList[[zip file "/data/app/com.daarayislam.app-yhUEt88ey2KT-S0gs0tx7Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.daarayislam.app-yhUEt88ey2KT-S0gs0tx7Q==/lib/x86, /data/app/com.daarayislam.app-yhUEt88ey2KT-S0gs0tx7Q==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/AndroidRuntime( 8528): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime( 8528): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8528): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8528): 	... 14 more
I/Process ( 8528): Sending signal. PID: 8528 SIG: 9
```

**Comment by kebsont** [comment]
Hello @gafsel , I tried to add these dependencies, but still got the same error, and I don't use videoPlayer.

```logs
W/Glide   ( 8528): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
D/NetworkSecurityConfig( 8528): Using Network Security Config from resource network_security_config debugBuild: true
W/myapp.ap( 8528): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, reflection, allowed)
W/myapp.ap( 8528): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
W/myapp.ap( 8528): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (greylist,core-platform-api, reflection, allowed)
D/AndroidRuntime( 8528): Shutting down VM
E/AndroidRuntime( 8528): FATAL EXCEPTION: main
E/AndroidRuntime( 8528): Process: com.myapp.app, PID: 8528
E/AndroidRuntime( 8528): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/exoplayer2/drm/DefaultDrmSessionManager$EventListener;
E/AndroidRuntime( 8528): 	at com.devbrackets.android.exomedia.core.audio.ExoAudioPlayer.<init>(ExoAudioPlayer.java:62)
E/AndroidRuntime( 8528): 	at com.devbrackets.android.exomedia.AudioPlayer.<init>(AudioPlayer.java:64)
E/AndroidRuntime( 8528): 	at com.devbrackets.android.exomedia.AudioPlayer.<init>(AudioPlayer.java:60)
E/AndroidRuntime( 8528): 	at org.gafs.flutter_plugin_playlist.playlist.AudioApi.<init>(AudioApi.java:25)
E/AndroidRuntime( 8528): 	at org.gafs.flutter_plugin_playlist.service.MediaService.onCreate(MediaService.java:23)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread.access$1500(ActivityThread.java:219)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
E/AndroidRuntime( 8528): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime( 8528): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 8528): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 8528): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8528): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 8528): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 8528): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.exoplayer2.drm.DefaultDrmSessionManager$EventListener" on path: DexPathList[[zip file "/data/app/com.myapp.app-yhUEt88ey2KT-S0gs0tx7Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp.app-yhUEt88ey2KT-S0gs0tx7Q==/lib/x86, /data/app/com.myapp.app-yhUEt88ey2KT-S0gs0tx7Q==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
E/AndroidRuntime( 8528): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime( 8528): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime( 8528): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime( 8528): 	... 14 more
I/Process ( 8528): Sending signal. PID: 8528 SIG: 9
```
